services:
  postgres:
    image: postgres:latest
    container_name: postgres_bratishka
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kirill123
      POSTGRES_DB: bratishka_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bratishka_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kirill123
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
